### ISSUE TITLE
Error when inserting Postmark unsubscribe tag

### ISSUE THREAD

**Issue by walseb** [dittofeed/dittofeed#993]
Hello!

I want to use the Postmark unsubscribe facilities, so I simply added this to my email:

```html
<a href="{{{ pm:unsubscribe }}}">Unsubscribe</a>
```

Which is standard postmark unsubscribe button syntax.

However, when I do this I get the following error and the preview goes blank:
```
Body Error: unexpected token at "{ pm:unsubscribe", ...
```

It seems I can't send the email with that error present.

I'm testing this in the create broadcast menu.

Thoughts?

Thanks!

**Comment by maxgurewitz** [comment]
@walseb dittofeed natively supports is own subscription implementation, any thoughts on using it?

https://docs.dittofeed.com/resources/subscription-groups#adding-unsubscribe-links-to-emails

> Body Error: unexpected token at "{ pm:unsubscribe", ...

Yes, I believe the issue is that the above syntax is conflicting with liquid. We may need to find a way to escape the outer `{`'s.

**Comment by walseb** [comment]
Thanks so much for the hint! I read up on liquid.

The solution is to do this:
```html
<a href="{% raw %} {{{ pm:unsubscribe }}} {% endraw %}">Unsubscribe</a>
```

I tried using the built-in subscription implementation, but I'm using a very slow server on a home IP, so I would rather use Postmark's subscription feature.

Thank you for the help and the excellent email platform!

**Comment by maxgurewitz** [comment]
Of course! :)
